### Schedule a day
POST http://localhost:8080/api/doctor/schedule
Content-Type: application/json
X-CorrelationId: test-correlation-id
X-CausationId: test-causation-id

{
  "date": "2022-10-10",
  "doctorId": "1234",
  "slots": [
    {
      "duration": "PT10m",
      "startTime": "14:30:00"
    },
    {
      "duration": "PT10m",
      "startTime": "14:40:00"
    },
    {
      "duration": "PT10m",
      "startTime": "14:50:00"
    }
  ]
}

### Get slots available on a date
GET http://localhost:8080/api/slots/2022-10-10/available

### Book a slot
POST http://localhost:8080/api/slots/1234_2022-10-10/book
Content-Type: application/json
X-CorrelationId: test-correlation-id
X-CausationId: test-causation-id

{
  "slotId": "c4b1f51a-d611-4ff6-bd57-6aad346104e8",
  "patientId": "John Doe"
}

### Cancel slot booking
POST http://localhost:8080/api/slots/1234_2022-10-10/cancel-booking
Content-Type: application/json
X-CorrelationId: test-correlation-id
X-CausationId: test-causation-id

{
  "slotId": "c4b1f51a-d611-4ff6-bd57-6aad346104e8",
  "reason": "No longer needed"
}

### Send day started event
POST http://localhost:8080/api/calendar/2022-10-11/day-started
Content-Type: application/json
X-CorrelationId: test-correlation-id-2
X-CausationId: test-causation-id-2
