### Schedule a day
POST http://localhost:8080/api/doctor/schedule
Content-Type: application/json
X-CorrelationId: test-correlation-id
X-CausationId: test-causation-id

{
  "date": "2020-10-06",
  "doctorId": "1234",
  "slots": [
    {
      "duration": "PT10m",
      "startTime": "14:30:00"
    },
    {
      "duration": "PT10m",
      "startTime": "14:40:00"
    },
    {
      "duration": "PT10m",
      "startTime": "14:50:00"
    }
  ]
}

### Get slots available on a date
GET http://localhost:8080/api/slots/2020-10-06/available

### Book a slot
POST http://localhost:8080/api/slots/1234_2020-10-06/book
Content-Type: application/json
X-CorrelationId: test-correlation-id
X-CausationId: test-causation-id

{
  "slotId": "150598bb-fc32-4490-8641-0c8acd012e82",
  "patientId": "John Doe"
}

### Cancel slot booking
POST http://localhost:8080/api/slots/1234_2020-10-06/cancel-booking
Content-Type: application/json
X-CorrelationId: test-correlation-id
X-CausationId: test-causation-id

{
  "slotId": "150598bb-fc32-4490-8641-0c8acd012e82",
  "reason": "No longer needed"
}

### Send day started event
POST http://localhost:8080/api/calendar/2020-10-07/day-started
Content-Type: application/json
X-CorrelationId: test-correlation-id
X-CausationId: test-causation-id
